# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,https://croppulse.onrender.com}

# AI Service (change after you deploy Python)
ai.service.url=${AI_SERVICE_URL:http://localhost:8000}

spring.application.name=CropPulse
server.port=${PORT:8080}

# Groq AI
groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.3-70b-versatile

# =========================
# MongoDB
# =========================
spring.data.mongodb.uri=${MONGODB_URI}

# =========================
# JWT
# =========================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# =========================
# Email
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Reset URL
app.reset.base-url=${RESET_BASE_URL:https://croppulse.onrender.com/reset-password?token=}
